ALTER TABLE items ADD COLUMN description VARCHAR(200) NULL,  
 ADD COLUMN brand VARCHAR(20) NULL,  
 ADD COLUMN color VARCHAR(20) NULL,
 ADD COLUMN category VARCHAR(20) NULL,
 ADD COLUMN size VARCHAR(20) NULL;  
